/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artifacts */
        get: operations["listArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["getArtifactDraft"];
        /**
         * Save Draft
         * @description Autosave the editable presentation. This does not create a revision.
         */
        put: operations["saveArtifactDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Revisions */
        get: operations["listArtifactRevisions"];
        put?: never;
        /**
         * Save Revision
         * @description Persist an immutable user revision. This does not place or change an order.
         */
        post: operations["saveArtifactRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/revisions/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Revision */
        get: operations["getArtifactRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bars */
        get: operations["getBars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat */
        post: operations["postChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/futures-contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Futures Contracts */
        get: operations["listFuturesContracts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["listInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Events */
        get: operations["listRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Run Features
         * @description Features whose chart annotations were stored with this run.
         *
         *     The rows are the calc 1.0.0 features the thesis cites. Levels are not recomputed here.
         */
        get: operations["listRunFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Workspace */
        get: operations["searchWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session-calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Session Calendars */
        get: operations["listSessionCalendars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["listSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /**
         * AdapterCapabilities
         * @description What a provider can honestly supply. The UI surfaces this next to every result.
         */
        AdapterCapabilities: {
            /**
             * Consolidated Equities
             * @description False for single-exchange (IEX-only) equity feeds.
             */
            consolidated_equities?: boolean | null;
            /** Coverage Note */
            coverage_note?: string | null;
            /**
             * Has Trades
             * @description False means exact volume profile is unavailable.
             */
            has_trades: boolean;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /** Provider */
            provider: string;
        };
        /** ArtifactDetail */
        ArtifactDetail: {
            /** Contract Code */
            contract_code?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Revision Id */
            current_revision_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Id */
            instrument_id?: string | null;
            /** Kind */
            kind: string;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ArtifactHit */
        ArtifactHit: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ArtifactSummary */
        ArtifactSummary: {
            /** Contract Code */
            contract_code?: string | null;
            /** Current Revision Id */
            current_revision_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Id */
            instrument_id?: string | null;
            /** Kind */
            kind: string;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Bar
         * @description One completed or forming OHLCV bar. ``origin_time`` is the bar's open time in UTC.
         */
        Bar: {
            /**
             * Close
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            close: string;
            /**
             * Contract Code
             * @description Listed contract code for futures bars; null otherwise.
             */
            contract_code?: string | null;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /**
             * High
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            high: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Is Complete
             * @description Only completed bars may produce confirmed signals.
             * @default true
             */
            is_complete: boolean;
            /**
             * Low
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            low: string;
            /**
             * Open
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            open: string;
            /**
             * Origin Time
             * Format: date-time
             */
            origin_time: string;
            /**
             * Origin Tz
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            origin_tz: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            /** Trade Count */
            trade_count?: number | null;
            /**
             * Volume
             * Format: decimal
             * @description Total traded size in the bar; decimals for crypto.
             */
            volume: string;
            /** Vwap */
            vwap?: string | null;
        };
        /**
         * BarSeries
         * @description A contiguous run of bars from one snapshot.
         */
        BarSeries: {
            /** Bars */
            bars: components["schemas"]["Bar"][];
            /** Contract Code */
            contract_code?: string | null;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
        };
        /** Catalyst */
        Catalyst: {
            /** Name */
            name: string;
            /**
             * Note
             * @default null
             */
            note: string | null;
            /**
             * Scheduled At
             * @default null
             */
            scheduled_at: string | null;
            /**
             * Source Id
             * @default null
             */
            source_id: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Client Message Id
             * @description Retries with the same id reuse the existing job instead of starting another.
             */
            client_message_id?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Dispatch
             * @description inline runs the job in this request. worker leaves it queued for the worker.
             * @default inline
             * @enum {string}
             */
            dispatch: "inline" | "worker";
            /**
             * Horizon
             * @default 2-5 sessions
             */
            horizon: string;
            /** Message */
            message: string;
            /** Recording Id */
            recording_id?: string | null;
            /** Symbol */
            symbol: string;
            /**
             * Timeframe
             * @default 5m
             * @enum {string}
             */
            timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
        };
        /** ConversationHit */
        ConversationHit: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CorrelatedMarket */
        CorrelatedMarket: {
            /**
             * Correlation
             * @description Aligned-return correlation when computed.
             * @default null
             */
            correlation: number | null;
            /**
             * Feature Id
             * @default null
             */
            feature_id: string | null;
            /**
             * Relationship
             * @description Plain-language description of the linkage.
             */
            relationship: string;
            /** Symbol */
            symbol: string;
            /**
             * Window Bars
             * @default null
             */
            window_bars: number | null;
        };
        /** DraftBody */
        DraftBody: {
            /** Base Revision Id */
            base_revision_id?: string | null;
            /** Presentation Markdown */
            presentation_markdown?: string | null;
            /** Structured */
            structured?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
        };
        /** DraftResponse */
        DraftResponse: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Base Revision Id */
            base_revision_id?: string | null;
            /** Presentation Markdown */
            presentation_markdown?: string | null;
            /** Structured */
            structured?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * EvidenceItem
         * @description A sourced claim. Retrieved content is evidence, never instructions.
         */
        EvidenceItem: {
            /** Claim */
            claim: string;
            /**
             * Excerpt Id
             * @default null
             */
            excerpt_id: string | null;
            /**
             * Published At
             * @default null
             */
            published_at: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Source Id
             * @default null
             */
            source_id: string | null;
            /**
             * Stance
             * @enum {string}
             */
            stance: "supporting" | "opposing";
            /**
             * Title
             * @default null
             */
            title: string | null;
            /**
             * Url
             * @default null
             */
            url: string | null;
        };
        /**
         * FeatureReference
         * @description A technical finding that resolves to a saved TA feature and its chart annotation.
         */
        FeatureReference: {
            /**
             * Annotation Id
             * @description Chart annotation id rendered from the same feature.
             * @default null
             */
            annotation_id: string | null;
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /** Summary */
            summary: string;
        };
        /**
         * FixtureLabel
         * @description Attached to everything produced by the fixture generator so it can never pass as live.
         */
        FixtureLabel: {
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Generator
             * @description Generator identifier, e.g. trading_core.fixtures.generator
             */
            generator: string;
            /**
             * Generator Version
             * @description Semantic version of the calculation that produced this object.
             * @example 1.0.0
             */
            generator_version: string;
            /**
             * Notice
             * @default Synthetic demonstration data generated deterministically from a seed. Not market data. Not investment research.
             */
            notice: string;
            /**
             * Provenance
             * @default fixture
             * @constant
             */
            provenance: "fixture";
            /** Seed */
            seed: number;
        };
        /**
         * FuturesContract
         * @description A listed futures contract with the metadata required by spec section 4.
         */
        FuturesContract: {
            /**
             * Contract Code
             * @example 6EZ6
             * @example GCZ6
             */
            contract_code: string;
            /**
             * Contract Month
             * @description Delivery month as YYYY-MM.
             * @example 2026-12
             */
            contract_month: string;
            /** Currency */
            currency: string;
            /**
             * Exchange
             * @example CME
             * @example COMEX
             * @example NYMEX
             */
            exchange: string;
            /**
             * Expiry Date
             * Format: date
             * @description Published expiration date for this root. For FX that is the value/delivery date, which can fall after last trade. For metals, energy and equity index it is the last trade date, not the end of a physical delivery window.
             */
            expiry_date: string;
            /**
             * First Notice Date
             * @description First notice day for physically delivered contracts; null if not applicable.
             */
            first_notice_date?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             * @description The root instrument this contract belongs to.
             */
            instrument_id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Last Trade Date
             * Format: date
             */
            last_trade_date: string;
            /**
             * Last Trade Time Local
             * @description Clock time in the session calendar's timezone when the expiring contract stops trading. Distinct from the daily settlement time (ES settles at 15:15 CT but stops trading at 08:30 CT on expiration Friday).
             */
            last_trade_time_local?: string | null;
            /**
             * Point Multiplier
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            point_multiplier: string;
            /**
             * Provenance
             * @default live
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Root
             * @example 6E
             * @example GC
             * @example CL
             * @example ES
             */
            root: string;
            /** Session Calendar Id */
            session_calendar_id: string;
            /**
             * Settlement Time Local
             * @description Daily settlement time in the calendar's timezone.
             */
            settlement_time_local?: string | null;
            /**
             * Settlement Type
             * @enum {string}
             */
            settlement_type: "cash" | "physical";
            /**
             * Tick Size
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            tick_size: string;
            /**
             * Tick Value
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            tick_value: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Data Revision */
            data_revision?: string | null;
            /** Fixtures Loaded */
            fixtures_loaded: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "fixture" | "live";
            /**
             * Order Write Capability
             * @description Always false: the MVP has no broker order-write path.
             * @default false
             * @constant
             */
            order_write_capability: false;
            /**
             * Provenance
             * @description Provenance of data this deployment serves by default.
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /** Service */
            service: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Instrument
         * @description A tradable or researchable symbol. Futures roots and continuous series are instruments;
         *     individual listed contracts are :class:`FuturesContract` rows that point back here.
         */
        Instrument: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "futures" | "equity" | "etf" | "crypto_spot" | "crypto_futures" | "event_contract";
            /**
             * Base Asset
             * @description Crypto base asset (e.g. BTC) when applicable.
             */
            base_asset?: string | null;
            /**
             * Currency
             * @example USD
             */
            currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Continuous
             * @description True for continuous futures series. Never treat a continuous symbol as a listed contract; volume profiles are never merged across expiries silently.
             * @default false
             */
            is_continuous: boolean;
            /**
             * Multiplier
             * Format: decimal
             * @description Point multiplier: cash value of a one-point move for one unit/contract.
             */
            multiplier: string;
            /** Name */
            name: string;
            /**
             * Provenance
             * @default live
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Quote Asset
             * @description Crypto quote asset (e.g. USD) when applicable.
             */
            quote_asset?: string | null;
            /**
             * Session Calendar Id
             * @description Key into ``session_calendars``.
             */
            session_calendar_id: string;
            /**
             * Symbol
             * @example 6E
             * @example SPY
             * @example BTC-USD
             */
            symbol: string;
            /**
             * Tick Size
             * Format: decimal
             * @description Minimum price increment in quote units.
             */
            tick_size: string;
            /**
             * Tick Value
             * Format: decimal
             * @description Cash value of one tick for one unit/contract, in ``currency``.
             */
            tick_value: string;
            /**
             * Venue
             * @description Exchange or venue code, e.g. CME, COMEX, NYMEX, ARCA, COINBASE.
             */
            venue: string;
        };
        /** Job */
        Job: {
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /**
             * Checkpoint
             * @description Stage outputs needed to resume after a restart.
             */
            checkpoint?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Conversation Id
             * @default null
             */
            conversation_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Finished At
             * @default null
             */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Idempotency Key
             * @description Deduplicates routine/instrument/feature/confirmation-time combinations.
             */
            idempotency_key: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "research" | "ta_scan" | "snapshot_capture" | "scheduled_briefing" | "hypothesis_check" | "csv_import" | "maintenance";
            /**
             * Last Error
             * @default null
             */
            last_error: string | null;
            /**
             * Lease Until
             * @default null
             */
            lease_until: string | null;
            /**
             * Leased By
             * @description Worker id holding the lease.
             * @default null
             */
            leased_by: string | null;
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
            /** Payload */
            payload?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Priority
             * @description Higher runs first.
             * @default 0
             */
            priority: number;
            /**
             * Routine Id
             * @default null
             */
            routine_id: string | null;
            /**
             * Scheduled For
             * Format: date-time
             */
            scheduled_for: string;
            /**
             * Scheduled Tz
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @default UTC
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            scheduled_tz: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "partial" | "completed" | "failed" | "cancelled" | "budget_exceeded";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        JsonValue: unknown;
        /**
         * Level
         * @description A named price produced by a detector (POC, VAH, zone bounds, swept level ...).
         */
        Level: {
            /**
             * Name
             * @example poc
             * @example vah
             * @example val
             * @example zone_upper
             */
            name: string;
            /**
             * Price
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            price: string;
            /**
             * Role
             * @default level
             * @enum {string}
             */
            role: "level" | "zone_upper" | "zone_lower" | "midpoint" | "threshold" | "node";
        };
        /**
         * MarketSnapshot
         * @description An immutable capture of bars and/or trades stored as Parquet. Every TA feature references
         *     the snapshot it was computed from through ``data_revision``.
         */
        MarketSnapshot: {
            /**
             * As Of
             * Format: date-time
             * @description Time the capture was taken.
             */
            as_of: string;
            /**
             * As Of Tz
             * @description IANA zone the capture was taken in; ``as_of`` itself is UTC.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            as_of_tz: string;
            /**
             * Content Hash
             * @description SHA-256 over the canonical row encoding; detects drift.
             */
            content_hash: string;
            /** Contract Code */
            contract_code?: string | null;
            /**
             * Coverage Note
             * @description e.g. 'IEX-only approximation' for single-exchange equity trades.
             */
            coverage_note?: string | null;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "bars" | "trades";
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Provider
             * @example fixture
             * @example databento
             * @example alpaca
             * @example coinbase
             */
            provider: string;
            /**
             * Range End
             * Format: date-time
             */
            range_end: string;
            /**
             * Range Start
             * Format: date-time
             */
            range_start: string;
            /** Row Count */
            row_count: number;
            /**
             * Storage Key
             * @description Object-store key of the Parquet file.
             */
            storage_key: string;
            /**
             * Timeframe
             * @description Timeframe for bar snapshots; null for trade snapshots.
             */
            timeframe?: ("1m" | "5m" | "15m" | "1h" | "4h" | "1d") | null;
        };
        /** Message */
        Message: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "developer" | "user" | "assistant" | "tool";
            /**
             * Tool Call Id
             * @default null
             */
            tool_call_id: string | null;
        };
        /** ModelRequest */
        ModelRequest: {
            /**
             * Instructions
             * @description Core model instruction (see spec section 6).
             */
            instructions: string;
            /**
             * Max Output Tokens
             * @default 4096
             */
            max_output_tokens: number;
            /** Messages */
            messages: components["schemas"]["Message"][];
            /**
             * Model
             * @description Server-configured model name.
             * @default null
             */
            model: string | null;
            /**
             * Recording Id
             * @description For RecordedProvider: replay this specific recording.
             * @default null
             */
            recording_id: string | null;
            /**
             * Response Schema
             * @description JSON Schema the model must satisfy (e.g. the Thesis contract).
             * @default null
             */
            response_schema: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Tool Results */
            tool_results?: components["schemas"]["ToolResult"][];
            /** Tools */
            tools?: components["schemas"]["ToolSpec"][];
        };
        /** ModelResponse */
        ModelResponse: {
            /**
             * Finish Reason
             * @enum {string}
             */
            finish_reason: "stop" | "tool_calls" | "length" | "content_filter" | "error";
            /**
             * Is Demonstration
             * @description True for recorded replays; the UI labels the result as demonstration output.
             */
            is_demonstration: boolean;
            /** Model */
            model: string | null;
            /**
             * Output Json
             * @default null
             */
            output_json: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Output Text
             * @default null
             */
            output_text: string | null;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "recorded" | "live";
            /** Provider */
            provider: string;
            /** Response Id */
            response_id: string;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            usage: components["schemas"]["Usage"];
        };
        /** RevisionDetail */
        RevisionDetail: {
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Change Kind */
            change_kind: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Demonstration */
            is_demonstration: boolean;
            /** Parent Revision Id */
            parent_revision_id?: string | null;
            /** Presentation Markdown */
            presentation_markdown: string;
            /** Provenance */
            provenance: string;
            /** Revision Number */
            revision_number: number;
            /** Run Id */
            run_id?: string | null;
            /** Structured */
            structured: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** RevisionSummary */
        RevisionSummary: {
            /** Change Kind */
            change_kind: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Demonstration */
            is_demonstration: boolean;
            /** Presentation Markdown */
            presentation_markdown: string;
            /** Provenance */
            provenance: string;
            /** Revision Number */
            revision_number: number;
        };
        /**
         * RiskCalculation
         * @description Hypothetical cost and risk figures. Futures amounts use verified point/tick values.
         */
        RiskCalculation: {
            /** Account Currency */
            account_currency: string;
            /** Assumptions */
            assumptions?: string[];
            /**
             * Contracts
             * @default null
             */
            contracts: number | null;
            /**
             * Estimated Costs
             * @default null
             */
            estimated_costs: string | null;
            /**
             * Is Hypothetical
             * @default true
             * @constant
             */
            is_hypothetical: true;
            /**
             * Point Value
             * @default null
             */
            point_value: string | null;
            /**
             * Reward To Risk
             * @default null
             */
            reward_to_risk: string | null;
            /**
             * Risk Per Contract
             * @default null
             */
            risk_per_contract: string | null;
            /**
             * Tick Value
             * @default null
             */
            tick_value: string | null;
            /**
             * Total Risk
             * @default null
             */
            total_risk: string | null;
        };
        /**
         * RollMapEntry
         * @description How a continuous series moved from one listed contract to the next.
         */
        RollMapEntry: {
            /**
             * Adjustment
             * @description Additive difference or multiplicative ratio applied to prior history.
             * @default null
             */
            adjustment: string | null;
            /** From Contract Code */
            from_contract_code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             * @description Continuous-series instrument this roll belongs to.
             */
            instrument_id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "none" | "back_adjust_difference" | "back_adjust_ratio" | "calendar";
            /**
             * Provenance
             * @default live
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Roll Date
             * Format: date
             */
            roll_date: string;
            /** Root */
            root: string;
            /** To Contract Code */
            to_contract_code: string;
        };
        /**
         * Run
         * @description One execution of a job. A run produces at most one artifact revision.
         */
        Run: {
            /** Artifact Revision Id */
            artifact_revision_id?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Current Stage */
            current_stage?: ("resolve_instrument" | "capture_snapshot" | "deterministic_ta" | "gather_context" | "synthesize" | "critique" | "validate" | "repair" | "persist" | "notify") | null;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /** Provider */
            provider: string;
            /** Stages Completed */
            stages_completed?: ("resolve_instrument" | "capture_snapshot" | "deterministic_ta" | "gather_context" | "synthesize" | "critique" | "validate" | "repair" | "persist" | "notify")[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "partial" | "completed" | "failed" | "cancelled" | "budget_exceeded";
            usage: components["schemas"]["Usage"];
        };
        /**
         * RunEvent
         * @description Structured timeline entry streamed to the UI and kept for audit.
         */
        RunEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Data */
            data?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Level
             * @default info
             * @enum {string}
             */
            level: "debug" | "info" | "warning" | "error";
            /** Message */
            message: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Sequence */
            sequence: number;
            /** Stage */
            stage?: ("resolve_instrument" | "capture_snapshot" | "deterministic_ta" | "gather_context" | "synthesize" | "critique" | "validate" | "repair" | "persist" | "notify") | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactHit"][];
            /** Conversations */
            conversations?: components["schemas"]["ConversationHit"][];
            /** Query */
            query: string;
        };
        /**
         * SessionCalendar
         * @description Versioned session definition referenced by every feature and snapshot.
         */
        SessionCalendar: {
            /**
             * Always Open
             * @description True for 24/7 venues such as spot crypto.
             * @default false
             */
            always_open: boolean;
            /**
             * Exchange Calendar Code
             * @description exchange_calendars code for holidays (e.g. CMES, XNYS); null for 24/7 venues.
             */
            exchange_calendar_code?: string | null;
            /** Holidays */
            holidays?: string[];
            /**
             * Id
             * @example cme_globex_fx
             * @example us_equity_rth
             */
            id: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Timezone
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            timezone: string;
            /** Trading Days */
            trading_days: ("mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun")[];
            /** Version */
            version: string;
            /** Windows */
            windows: components["schemas"]["SessionWindow"][];
        };
        /**
         * SessionWindow
         * @description One trading window inside a session day, in the calendar's local timezone.
         */
        SessionWindow: {
            /**
             * Close Time
             * Format: time
             */
            close_time: string;
            /**
             * Kind
             * @description 'trading' windows produce bars; 'sub_session' windows (e.g. RTH inside Globex) only define session levels.
             * @default trading
             * @enum {string}
             */
            kind: "trading" | "sub_session" | "break" | "settlement_window";
            /**
             * Name
             * @example globex
             * @example rth
             * @example maintenance_break
             * @example settlement
             */
            name: string;
            /**
             * Open Time
             * Format: time
             */
            open_time: string;
            /**
             * Opens Previous Day
             * @description True when the window opens on the calendar day before the session date (e.g. Globex opens 17:00 CT the prior evening).
             * @default false
             */
            opens_previous_day: boolean;
        };
        /**
         * TAEvent
         * @description The idempotent detection row for one feature.
         *
         *     Unique on (instrument, contract_code, timeframe, detector, calc_version, origin_time,
         *     data_revision). ``contract_code`` is part of the key so two listed months of one root can
         *     share an origin time. ``event_type`` is always ``confirmed``; later lifecycle is a
         *     :class:`TAFeatureTransition`, which keeps re-detection from rewriting an earlier log.
         */
        TAEvent: {
            /**
             * Calc Version
             * @description Semantic version of the calculation that produced this object.
             * @example 1.0.0
             */
            calc_version: string;
            /**
             * Contract Code
             * @default null
             */
            contract_code: string | null;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /** Details */
            details?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Detector
             * @enum {string}
             */
            detector: "volume_profile" | "fvg" | "liquidity_sweep" | "bos" | "order_block" | "rsi_divergence" | "swing_pivot" | "liquidity_pool" | "atr" | "rsi" | "vwap" | "session_levels" | "correlation";
            /**
             * Direction
             * @enum {string}
             */
            direction: "bullish" | "bearish" | "neutral";
            /**
             * Event Time
             * Format: date-time
             * @description Close time of the bar that produced the event.
             */
            event_time: string;
            /**
             * Event Type
             * @default confirmed
             * @constant
             */
            event_type: "confirmed";
            /**
             * Event Tz
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            event_tz: string;
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Levels */
            levels?: components["schemas"]["Level"][];
            /**
             * Origin Time
             * Format: date-time
             */
            origin_time: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
        };
        /**
         * TAFeature
         * @description Versioned feature object. ``origin_time`` is when the pattern formed; ``confirmation_time``
         *     is when it became knowable (e.g. a pivot at bar i confirms at i+3). ``as_of`` is the last
         *     completed bar the detector saw.
         */
        TAFeature: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * As Of Tz
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            as_of_tz: string;
            /**
             * Calc Version
             * @description Semantic version of the calculation that produced this object.
             * @example 1.0.0
             */
            calc_version: string;
            /**
             * Confirmation Time
             * @description Null while the feature is still pending.
             */
            confirmation_time?: string | null;
            /**
             * Confirmation Tz
             * @description Set exactly when ``confirmation_time`` is set.
             */
            confirmation_tz?: string | null;
            /** Contract Code */
            contract_code?: string | null;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /**
             * Details
             * @description Detector-specific payload (histogram bins, displacement tag, fill depth ...).
             */
            details?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Detector
             * @enum {string}
             */
            detector: "volume_profile" | "fvg" | "liquidity_sweep" | "bos" | "order_block" | "rsi_divergence" | "swing_pivot" | "liquidity_pool" | "atr" | "rsi" | "vwap" | "session_levels" | "correlation";
            /**
             * Direction
             * @enum {string}
             */
            direction: "bullish" | "bearish" | "neutral";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Levels */
            levels: components["schemas"]["Level"][];
            /**
             * Origin Time
             * Format: date-time
             */
            origin_time: string;
            /**
             * Origin Tz
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            origin_tz: string;
            /**
             * Parameters
             * @description Exact detector parameters used for this calculation.
             */
            parameters?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Session
             * @enum {string}
             */
            session: "current_session" | "prior_session" | "overnight" | "rth" | "eth" | "anchored" | "fixed_range" | "composite";
            /** Session Calendar Id */
            session_calendar_id: string;
            /** Session Calendar Version */
            session_calendar_version: string;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "confirmed" | "touched" | "midpoint_touched" | "partially_filled" | "filled" | "revisited" | "consumed" | "invalidated" | "expired";
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            /**
             * Warnings
             * @description e.g. 'approximation: bar-derived volume', 'roll window excluded'.
             */
            warnings?: string[];
        };
        /**
         * TAFeatureTransition
         * @description Post-confirmation lifecycle (touch, fill, invalidation) for one data revision.
         *
         *     Not part of the ``ta_events`` idempotency key. ``feature_id`` is the id the detector assigned
         *     on the :class:`TAFeature`.
         */
        TAFeatureTransition: {
            /**
             * Bar Time
             * Format: date-time
             * @description Close time of the completed bar that caused this.
             */
            bar_time: string;
            /**
             * Bar Tz
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            bar_tz: string;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /** Details */
            details?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Feature Id
             * Format: uuid
             */
            feature_id: string;
            /**
             * From State
             * @enum {string}
             */
            from_state: "pending" | "confirmed" | "touched" | "midpoint_touched" | "partially_filled" | "filled" | "revisited" | "consumed" | "invalidated" | "expired";
            /**
             * To State
             * @enum {string}
             */
            to_state: "pending" | "confirmed" | "touched" | "midpoint_touched" | "partially_filled" | "filled" | "revisited" | "consumed" | "invalidated" | "expired";
        };
        /** Thesis */
        Thesis: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "futures" | "equity" | "etf" | "crypto_spot" | "crypto_futures" | "event_contract";
            /** Catalysts */
            catalysts?: components["schemas"]["Catalyst"][];
            /**
             * Contract Code
             * @description Actual futures contract when applicable.
             * @default null
             */
            contract_code: string | null;
            /** Correlated Markets */
            correlated_markets?: components["schemas"]["CorrelatedMarket"][];
            /**
             * Expires At
             * @default null
             */
            expires_at: string | null;
            /**
             * Horizon
             * @example intraday
             * @example 2-5 sessions
             * @example swing
             */
            horizon: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Is Demonstration
             * @description True whenever provenance is not live; UI must label it prominently.
             */
            is_demonstration: boolean;
            /** Macro Context */
            macro_context: string;
            /** Market Narrative */
            market_narrative: string;
            /** Missing Data */
            missing_data?: string[];
            /** Opposing Evidence */
            opposing_evidence?: components["schemas"]["EvidenceItem"][];
            plan: components["schemas"]["TradePlan"];
            /**
             * Presentation Markdown
             * @description Editable presentation of this thesis.
             */
            presentation_markdown: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /** Rationale */
            rationale: string;
            /** @default null */
            risk: components["schemas"]["RiskCalculation"] | null;
            /**
             * Run Id
             * @default null
             */
            run_id: string | null;
            /**
             * Stance
             * @enum {string}
             */
            stance: "bullish" | "bearish" | "neutral" | "insufficient_evidence";
            /** Supporting Evidence */
            supporting_evidence?: components["schemas"]["EvidenceItem"][];
            /** Symbol */
            symbol: string;
            /** Technical Findings */
            technical_findings: components["schemas"]["FeatureReference"][];
            /** Uncertainty */
            uncertainty: string;
            validation: components["schemas"]["ValidationResult"];
            /** Venue */
            venue: string;
            versions: components["schemas"]["ThesisVersions"];
        };
        /** ThesisVersions */
        ThesisVersions: {
            /** Harness Version */
            harness_version: string;
            /**
             * Model
             * @description Model name as configured server-side.
             * @default null
             */
            model: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Tool Versions */
            tool_versions?: {
                [key: string]: string;
            };
        };
        /** ToolCall */
        ToolCall: {
            /** Arguments */
            arguments: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ToolResult */
        ToolResult: {
            /** Call Id */
            call_id: string;
            /**
             * Is Error
             * @default false
             */
            is_error: boolean;
            /** Name */
            name: string;
            output: components["schemas"]["JsonValue"];
        };
        /**
         * ToolSpec
         * @description A typed function tool. ``parameters`` is a JSON Schema object; the server enforces limits.
         */
        ToolSpec: {
            /**
             * Counts As External Retrieval
             * @description True for web/search/source fetches subject to the 12-call cap.
             * @default false
             */
            counts_as_external_retrieval: boolean;
            /** Description */
            description: string;
            /**
             * Max Calls Per Run
             * @default 12
             */
            max_calls_per_run: number;
            /** Name */
            name: string;
            /** Parameters */
            parameters: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Version */
            version: string;
        };
        /**
         * Trade
         * @description A single trade print. ``side`` is the aggressor side only when the venue reports it;
         *     price-up/price-down volume is never labeled as buy/sell.
         */
        Trade: {
            /**
             * Contract Code
             * @default null
             */
            contract_code: string | null;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Price
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            price: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /**
             * Sequence
             * @description Monotonic sequence within the snapshot.
             */
            sequence: number;
            /**
             * Side
             * @default unknown
             * @enum {string}
             */
            side: "buy" | "sell" | "unknown";
            /**
             * Size
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             */
            size: string;
            /**
             * Trade Time
             * Format: date-time
             */
            trade_time: string;
            /**
             * Trade Tz
             * @description IANA timezone name of the original timestamp, e.g. America/Chicago.
             * @example America/Chicago
             * @example America/New_York
             * @example UTC
             */
            trade_tz: string;
            /** Venue */
            venue: string;
        };
        /**
         * TradeBatch
         * @description Trade prints from one snapshot, ordered by ``sequence``.
         */
        TradeBatch: {
            /**
             * Contract Code
             * @default null
             */
            contract_code: string | null;
            /**
             * Data Revision
             * @description Identifier of the exact data snapshot a calculation ran against. Re-running on the same revision must be idempotent.
             */
            data_revision: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "fixture" | "recorded" | "live";
            /** Trades */
            trades: components["schemas"]["Trade"][];
        };
        /**
         * TradePlan
         * @description Conditional plan. Any unsupported element stays null with ``unset_reason`` explaining why.
         */
        TradePlan: {
            /**
             * Entry
             * @default null
             */
            entry: string | null;
            /**
             * Invalidation
             * @default null
             */
            invalidation: string | null;
            /** Monitoring Criteria */
            monitoring_criteria?: string[];
            /**
             * Target
             * @default null
             */
            target: string | null;
            /**
             * Unset Reason
             * @description Required when entry, invalidation or target is null.
             * @default null
             */
            unset_reason: string | null;
        };
        /** Usage */
        Usage: {
            /** Actual Cost Usd */
            actual_cost_usd?: string | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Reserved Cost Usd
             * Format: decimal
             * @description Exact decimal encoded as a string (money, prices, sizes).
             * @default 0
             */
            reserved_cost_usd: string;
            /**
             * Retrieval Calls
             * @default 0
             */
            retrieval_calls: number;
        };
        /**
         * UserRevisionBody
         * @description User save. Numerical fields overlay the parent thesis; feature levels are left untouched.
         */
        UserRevisionBody: {
            /**
             * Base Revision Id
             * Format: uuid
             */
            base_revision_id: string;
            /** Contracts */
            contracts?: number | null;
            /** Entry */
            entry?: string | null;
            /** Estimated Costs */
            estimated_costs?: string | null;
            /** Invalidation */
            invalidation?: string | null;
            /** Presentation Markdown */
            presentation_markdown: string;
            /**
             * Stance
             * @enum {string}
             */
            stance: "bullish" | "bearish" | "neutral" | "insufficient_evidence";
            /** Target */
            target?: string | null;
            /** Unset Reason */
            unset_reason?: string | null;
        };
        /** ValidationCheck */
        ValidationCheck: {
            /**
             * Detail
             * @default null
             */
            detail: string | null;
            /**
             * Name
             * @example schema
             * @example numeric_crosscheck
             * @example evidence_ids_exist
             */
            name: string;
            /** Passed */
            passed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Checks */
            checks: components["schemas"]["ValidationCheck"][];
            /** Passed */
            passed: boolean;
            /**
             * Repair Attempted
             * @default false
             */
            repair_attempted: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listArtifacts: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getArtifactDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saveArtifactDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listArtifactRevisions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saveArtifactRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRevisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getArtifactRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getBars: {
        parameters: {
            query: {
                end?: string | null;
                limit?: number;
                start?: string | null;
                symbol: string;
                timeframe?: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterCapabilities"];
                };
            };
        };
    };
    postChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listFuturesContracts: {
        parameters: {
            query?: {
                root?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FuturesContract"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listInstruments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"][];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                conversation_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRunFeatures: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TAFeature"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    searchWorkspace: {
        parameters: {
            query: {
                limit?: number;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSessionCalendars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCalendar"][];
                };
            };
        };
    };
    listSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketSnapshot"][];
                };
            };
        };
    };
}
